#
# Generated by Precision RTL Synthesis 64-bit 2021.2.0.8 (Release Production Release, compiled Sun Jan 23 22:08:46 PST 2022)
#

## Setup project
file delete -force {vivado_impl_1/vivado_impl_1.xpr}
create_project vivado_impl_1 {vivado_impl_1} -part 7Z010CLG400-1
set_property design_mode GateLvl [current_fileset]
add_file -scan_for_includes {vivado_impl_1}
set_property edif_top_file {Z_I2C_IP.edf} [current_fileset]
link_design 
read_xdc  {Z_I2C_IP.xdc}


## Report project
report_property [current_project]
report_property [current_fileset]
report_property [current_fileset -constrset]

## P&R

if { [catch {opt_design -sweep -propconst -quiet} result] } {
  return -code error -errorinfo "can not run opt_design exiting ... $result"
}
if { [catch {place_design} result] } {
  return -code error -errorinfo "can not run place_design exiting ... $result"
}
if { [catch {phys_opt_design} result] } {
  return -code error -errorinfo "can not run phys_opt_design exiting ... $result"
}
if { [catch {route_design} result] } {
  return -code error -errorinfo "can not run route_design exiting ... $result"
}
## Output files and reports
write_checkpoint {vivado_impl_1/Z_I2C_IP_routed.dcp}
write_xdef {vivado_impl_1/routed_Z_I2C_IP.xdef}
report_timing -path_type full_clock_expanded -sort_by group -nworst 30 -file {vivado_impl_1/Z_I2C_IP_timing.twr}
report_timing -path_type full_clock_expanded -sort_by group -rise_from * -rise_to * -file {vivado_impl_1/Z_I2C_IP_short_timing.twr}
report_timing -path_type full_clock_expanded -sort_by group -fall_from * -fall_to * -file {vivado_impl_1/Z_I2C_IP_short_timing.twr} -append
report_timing -path_type full_clock_expanded -sort_by group -rise_from * -fall_to * -file {vivado_impl_1/Z_I2C_IP_short_timing.twr} -append
report_timing -path_type full_clock_expanded -sort_by group -fall_from * -rise_to * -file {vivado_impl_1/Z_I2C_IP_short_timing.twr} -append
report_timing_summary -file {vivado_impl_1/Z_I2C_IP_sum_timing.twr}
report_utilization -file {vivado_impl_1/Z_I2C_IP_utilization.rpt}
report_clock_utilization -file {vivado_impl_1/Z_I2C_IP_clock_utilization.rpt}
report_io -file {vivado_impl_1/Z_I2C_IP_io.rpt}
exit

