-- VHDL Entity Projet_I2CIP_lib.Controleur_I2C_Testeur.symbol
--
-- Created:
--          by - E21C396C.UNKNOWN (irc107-04)
--          at - 14:01:56 17/11/2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
LIBRARY Projet_I2CIP_lib;
USE Projet_I2CIP_lib.I2C_Package.ALL;

ENTITY Controleur_I2C_Testeur IS
   PORT( 
      SCK : OUT    DefBit;
      SDA : INOUT  DefBit
   );

-- Declarations

END Controleur_I2C_Testeur ;

--
-- VHDL Architecture Projet_I2CIP_lib.Controleur_I2C_Testeur.struct
--
-- Created:
--          by - E21C396C.UNKNOWN (irc107-04)
--          at - 14:38:11 17/11/2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
LIBRARY Projet_I2CIP_lib;
USE Projet_I2CIP_lib.I2C_Package.ALL;


ARCHITECTURE struct OF Controleur_I2C_Testeur IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL Addr  : DefAddr;
   SIGNAL Clk   : DefBit;
   SIGNAL Dbus  : DefDbus;
   SIGNAL RnW   : DefBit;
   SIGNAL nAS   : DefBit;
   SIGNAL nBE0  : DefBit;
   SIGNAL nBE1  : DefBit;
   SIGNAL nRst  : DefBit;
   SIGNAL nWait : DefBit;


   -- Component Declarations
   COMPONENT Environnement
   PORT (
      Addr  : OUT    DefAddr ;
      Clk   : OUT    DefBit ;
      Dbus  : OUT    DefDbus ;
      RnW   : OUT    DefBit ;
      nAS   : OUT    DefBit ;
      nBE0  : OUT    DefBit ;
      nBE1  : OUT    DefBit ;
      nRst  : OUT    DefBit ;
      nWait : OUT    DefBit 
   );
   END COMPONENT;
   COMPONENT I2C_IP
   PORT (
      Addr  : IN     DefAddr ;
      Clk   : IN     DefBit ;
      RnW   : IN     DefBit ;
      nAS   : IN     DefBit ;
      nBE0  : IN     DefBit ;
      nBE1  : IN     DefBit ;
      nRst  : IN     DefBit ;
      nWait : IN     DefBit ;
      SCK   : OUT    DefBit ;
      Dbus  : INOUT  DefDbus ;
      SDA   : INOUT  DefBit 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : Environnement USE ENTITY Projet_I2CIP_lib.Environnement;
   FOR ALL : I2C_IP USE ENTITY Projet_I2CIP_lib.I2C_IP;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : Environnement
      PORT MAP (
         Addr  => Addr,
         Clk   => Clk,
         Dbus  => Dbus,
         RnW   => RnW,
         nAS   => nAS,
         nBE0  => nBE0,
         nBE1  => nBE1,
         nRst  => nRst,
         nWait => nWait
      );
   U_1 : I2C_IP
      PORT MAP (
         Addr  => Addr,
         Clk   => Clk,
         RnW   => RnW,
         nAS   => nAS,
         nBE0  => nBE0,
         nBE1  => nBE1,
         nRst  => nRst,
         nWait => nWait,
         SCK   => SCK,
         Dbus  => Dbus,
         SDA   => SDA
      );

END struct;
