-- VHDL Entity Projet_I2CIP_lib.Emission_Reception.generatedInstance
--
-- Created:
--          by - E21C396C.UNKNOWN (irc107-04)
--          at - 15:54:41 17/11/2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
LIBRARY Projet_I2CIP_lib;
USE Projet_I2CIP_lib.I2C_Package.ALL;

ENTITY Emission_Reception IS
   PORT( 
      Clk          : IN     DefBit;
      Config       : IN     DefConfig;
      DataReceived : OUT    DefData;
      DataToSend   : IN     DefData;
      nRst         : IN     DefBit;
      SCK          : OUT    DefBit;
      SCK_intern   : IN     DefBit;
      SDA          : INOUT  DefBit;
      Status       : OUT    DefStatus
   );

END Emission_Reception ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF Emission_Reception IS 
BEGIN


END generatedInstance;
