-- VHDL Entity Projet_I2CIP_lib.Environnement.generatedInstance
--
-- Created:
--          by - E21C396C.UNKNOWN (irc107-04)
--          at - 14:00:40 17/11/2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
LIBRARY Projet_I2CIP_lib;
USE Projet_I2CIP_lib.I2C_Package.ALL;

ENTITY Environnement IS
   PORT( 
      Addr  : OUT    DefAddr;
      Clk   : OUT    DefBit;
      Dbus  : OUT    DefDbus;
      nAS   : OUT    DefBit;
      nBE0  : OUT    DefBit;
      nBE1  : OUT    DefBit;
      nRst  : OUT    DefBit;
      nWait : OUT    DefBit
   );

END Environnement ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF Environnement IS 
BEGIN


END generatedInstance;
