-- VHDL Entity Projet_I2CIP_lib.GestionHorloge.generatedInstance
--
-- Created:
--          by - E21C396C.UNKNOWN (irc107-04)
--          at - 15:54:41 17/11/2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
LIBRARY Projet_I2CIP_lib;
USE Projet_I2CIP_lib.I2C_Package.ALL;

ENTITY GestionHorloge IS
   PORT( 
      Clk               : IN     DefBit;
      nRst              : IN     DefBit;
      SCK_intern        : OUT    DefBit;
      Transfert_Request : IN     DefBit
   );

END GestionHorloge ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF GestionHorloge IS 
BEGIN


END generatedInstance;
