-- VHDL Entity Projet_I2CIP_lib.I2C_IP.interface
--
-- Created:
--          by - E21C396C.UNKNOWN (irc107-04)
--          at - 15:54:41 17/11/2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
LIBRARY Projet_I2CIP_lib;
USE Projet_I2CIP_lib.I2C_Package.ALL;

ENTITY I2C_IP IS
   PORT( 
      Addr  : IN     DefAddr;
      Clk   : IN     DefBit;
      RnW   : IN     DefBit;
      nAS   : IN     DefBit;
      nBE0  : IN     DefBit;
      nBE1  : IN     DefBit;
      nRst  : IN     DefBit;
      nWait : IN     DefBit;
      SCK   : OUT    DefBit;
      Dbus  : INOUT  DefDbus;
      SDA   : INOUT  DefBit
   );

-- Declarations

END I2C_IP ;

--
-- VHDL Architecture Projet_I2CIP_lib.I2C_IP.struct
--
-- Created:
--          by - E21C396C.UNKNOWN (irc107-04)
--          at - 15:54:41 17/11/2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
LIBRARY Projet_I2CIP_lib;
USE Projet_I2CIP_lib.I2C_Package.ALL;


ARCHITECTURE struct OF I2C_IP IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL Config            : DefConfig;
   SIGNAL DataReceived      : DefData;
   SIGNAL DataToSend        : DefData;
   SIGNAL SCK_intern        : DefBit;
   SIGNAL Status            : DefStatus;
   SIGNAL Transfert_Request : DefBit;


   -- Component Declarations
   COMPONENT Emission_Reception
   PORT (
      Clk          : IN     DefBit;
      Config       : IN     DefConfig;
      DataToSend   : IN     DefData;
      SCK_intern   : IN     DefBit;
      nRst         : IN     DefBit;
      DataReceived : OUT    DefData;
      SCK          : OUT    DefBit;
      Status       : OUT    DefStatus;
      SDA          : INOUT  DefBit
   );
   END COMPONENT;
   COMPONENT GestionHorloge
   PORT (
      Clk               : IN     DefBit;
      Transfert_Request : IN     DefBit;
      nRst              : IN     DefBit;
      SCK_intern        : OUT    DefBit
   );
   END COMPONENT;
   COMPONENT Interface
   PORT (
      Addr              : IN     DefAddr ;
      Clk               : IN     DefBit ;
      DataReceived      : IN     DefData ;
      RnW               : IN     DefBit ;
      Status            : IN     DefStatus ;
      nAS               : IN     DefBit ;
      nBE0              : IN     DefBit ;
      nBE1              : IN     DefBit ;
      nRst              : IN     DefBit ;
      nWait             : IN     DefBit ;
      Config            : OUT    DefConfig ;
      DataToSend        : OUT    DefData ;
      Transfert_Request : OUT    DefBit ;
      Dbus              : INOUT  DefDbus 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : Emission_Reception USE ENTITY Projet_I2CIP_lib.Emission_Reception;
   FOR ALL : GestionHorloge USE ENTITY Projet_I2CIP_lib.GestionHorloge;
   FOR ALL : Interface USE ENTITY Projet_I2CIP_lib.Interface;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_1 : Emission_Reception
      PORT MAP (
         Clk          => Clk,
         Config       => Config,
         DataToSend   => DataToSend,
         SCK_intern   => SCK_intern,
         nRst         => nRst,
         DataReceived => DataReceived,
         SCK          => SCK,
         Status       => Status,
         SDA          => SDA
      );
   U_2 : GestionHorloge
      PORT MAP (
         Clk               => Clk,
         Transfert_Request => Transfert_Request,
         nRst              => nRst,
         SCK_intern        => SCK_intern
      );
   U_0 : Interface
      PORT MAP (
         Addr              => Addr,
         Clk               => Clk,
         DataReceived      => DataReceived,
         RnW               => RnW,
         Status            => Status,
         nAS               => nAS,
         nBE0              => nBE0,
         nBE1              => nBE1,
         nRst              => nRst,
         nWait             => nWait,
         Config            => Config,
         DataToSend        => DataToSend,
         Transfert_Request => Transfert_Request,
         Dbus              => Dbus
      );

END struct;
