-- VHDL Entity Projet_I2CIP_lib.Interface.generatedInstance
--
-- Created:
--          by - E21C396C.UNKNOWN (irc107-04)
--          at - 14:23:41 17/11/2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
LIBRARY Projet_I2CIP_lib;
USE Projet_I2CIP_lib.I2C_Package.ALL;

ENTITY Interface IS
   PORT( 
      Addr              : IN     DefAddr;
      Clk               : IN     DefBit;
      Config            : OUT    DefConfig;
      DataReceived      : IN     DefData;
      DataToSend        : OUT    DefData;
      Dbus              : IN     DefDbus;
      nAS               : IN     DefBit;
      nBE0              : IN     DefBit;
      nBE1              : IN     DefBit;
      nRst              : IN     DefBit;
      nWait             : IN     DefBit;
      RnW               : IN     DefBit;
      Status            : IN     DefStatus;
      Transfert_Request : OUT    DefBit
   );

END Interface ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF Interface IS 
BEGIN


END generatedInstance;
