-- VHDL Entity Projet_I2CIP_lib.Z_Controleur_I2C.symbol
--
-- Created:
--          by - CHAIMA.UNKNOWN (LAPTOP-I71U7FVH)
--          at - 17:43:39 26/11/2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
LIBRARY Projet_I2CIP_lib;
USE Projet_I2CIP_lib.I2C_Package.ALL;

ENTITY Z_Controleur_I2C IS
   PORT( 
      SCK : OUT    DefBit
   );

-- Declarations

END Z_Controleur_I2C ;

--
-- VHDL Architecture Projet_I2CIP_lib.Z_Controleur_I2C.struct
--
-- Created:
--          by - CHAIMA.UNKNOWN (LAPTOP-I71U7FVH)
--          at - 19:27:26 02/12/2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
LIBRARY Projet_I2CIP_lib;
USE Projet_I2CIP_lib.I2C_Package.ALL;
USE ieee.std_logic_unsigned.all;


ARCHITECTURE struct OF Z_Controleur_I2C IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL Addr  : DefAddr;
   SIGNAL Clk   : DefBit;
   SIGNAL Dbus  : DefDbus;
   SIGNAL RnW   : DefBit;
   SIGNAL SDA   : DefBit;
   SIGNAL nAS   : DefBit;
   SIGNAL nBE0  : DefBit;
   SIGNAL nBE1  : DefBit;
   SIGNAL nRst  : DefBit;
   SIGNAL nWait : DefBit;


   -- Component Declarations
   COMPONENT Z_Environnement2
   PORT (
      Dbus  : INOUT  DefDbus ;
      Addr  : OUT    DefAddr ;
      Clk   : OUT    DefBit ;
      RnW   : OUT    DefBit ;
      nAS   : OUT    DefBit ;
      nBE0  : OUT    DefBit ;
      nBE1  : OUT    DefBit ;
      nRst  : OUT    DefBit ;
      nWait : OUT    DefBit ;
      SDA   : INOUT  DefBit 
   );
   END COMPONENT;
   COMPONENT Z_I2C_IP
   PORT (
      Addr  : IN     DefAddr ;
      Clk   : IN     DefBit ;
      RnW   : IN     DefBit ;
      nAS   : IN     DefBit ;
      nBE0  : IN     DefBit ;
      nBE1  : IN     DefBit ;
      nRst  : IN     DefBit ;
      nWait : IN     DefBit ;
      SCK   : OUT    DefBit ;
      Dbus  : INOUT  DefDbus ;
      SDA   : INOUT  DefBit 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : Z_Environnement2 USE ENTITY Projet_I2CIP_lib.Z_Environnement2;
   FOR ALL : Z_I2C_IP USE ENTITY Projet_I2CIP_lib.Z_I2C_IP;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : Z_Environnement2
      PORT MAP (
         Dbus  => Dbus,
         Addr  => Addr,
         Clk   => Clk,
         RnW   => RnW,
         nAS   => nAS,
         nBE0  => nBE0,
         nBE1  => nBE1,
         nRst  => nRst,
         nWait => nWait,
         SDA   => SDA
      );
   U_1 : Z_I2C_IP
      PORT MAP (
         Addr  => Addr,
         Clk   => Clk,
         RnW   => RnW,
         nAS   => nAS,
         nBE0  => nBE0,
         nBE1  => nBE1,
         nRst  => nRst,
         nWait => nWait,
         SCK   => SCK,
         Dbus  => Dbus,
         SDA   => SDA
      );

END struct;
