-- VHDL Entity Projet_I2CIP_lib.Z_Emission_Reception.generatedInstance
--
-- Created:
--          by - CHAIMA.UNKNOWN (LAPTOP-I71U7FVH)
--          at - 12:43:31 19/11/2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2018.2 (Build 19)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
LIBRARY Projet_I2CIP_lib;
USE Projet_I2CIP_lib.I2C_Package.ALL;

ENTITY Z_Emission_Reception IS
   PORT( 
      Clk          : IN     DefBit;
      Config       : IN     DefConfig;
      DataReceived : OUT    DefData;
      DataToSend   : IN     DefData;
      nRst         : IN     DefBit;
      SCK          : OUT    DefBit;
      SCK_intern   : IN     DefBit;
      SDA          : INOUT  DefBit;
      Status       : OUT    DefStatus
   );

END Z_Emission_Reception ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF Z_Emission_Reception IS 
BEGIN


END generatedInstance;
