-- VHDL Entity Projet_I2CIP_lib.Z_I2C_IP.generatedInstance
--
-- Created:
--          by - CHAIMA.UNKNOWN (LAPTOP-I71U7FVH)
--          at - 22:11:47 18/11/2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2018.2 (Build 19)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
LIBRARY Projet_I2CIP_lib;
USE Projet_I2CIP_lib.I2C_Package.ALL;

ENTITY Z_I2C_IP IS
   PORT( 
      Addr  : IN     DefAddr;
      Clk   : IN     DefBit;
      Dbus  : INOUT  DefDbus;
      nAS   : IN     DefBit;
      nBE0  : IN     DefBit;
      nBE1  : IN     DefBit;
      nRst  : IN     DefBit;
      nWait : IN     DefBit;
      RnW   : IN     DefBit;
      SCK   : OUT    DefBit;
      SDA   : INOUT  DefBit
   );

END Z_I2C_IP ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF Z_I2C_IP IS 
BEGIN


END generatedInstance;
